name: Deploy to WordPress.org
# on:
#     push:
#         tags:
#             - '*'
on:
    push:
        branches:
            - master
jobs:
    deploy_wordpress_org:
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '5.3'
                  tools: 'composer'
            - name: Install plugin dependancies
              run: |
                  composer install --no-dev
            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@master
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: better-admin-users-search
                  VERSION: 1.1.1
