name: Plugin asset/readme update
on:
    push:
        branches:
            - master
jobs:
    update_wordpress_org:
        name: Push changes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '5.3'
                  tools: 'composer'
            - name: Install plugin dependancies
              run: |
                  composer install --no-dev
            - name: WordPress.org plugin asset/readme update
              uses: 10up/action-wordpress-plugin-asset-update@master
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: better-admin-users-search
